module dual_port_tb();
reg clk;
reg rst;
reg we_a;
reg [2:0] addr_a;
reg [7:0] datain_a;
reg we_b;
reg [2:0] addr_b;
reg [7:0] datain_b;
wire [7:0] dataout_a;
wire [7:0] dataout_b;


dual_port dut(clk,rst,we_a,addr_a,datain_a,we_b,addr_b,datain_b,dataout_a,dataout_b);

initial begin
clk=0;
forever #5 clk=~clk;
end

initial begin
	$dumpfile("dual_port.vcd");
	$dumpvars(0,dual_port_tb);
rst=1;
we_a=0;we_b=0;
addr_a=0;addr_b=0;
datain_a=0;datain_b=0;

#10;
rst=0;
we_a=1;addr_a=2;
datain_a=8'h2C;

we_b=1;addr_b=4;
datain_b=8'h44;

#10;
we_a=0;
we_b=0;
addr_a=2;
addr_b=4;
#10;

$display("Port A read=%h",dataout_a);
$display("Port B read=%h",dataout_b);
#10;
$finish;
end
endmodule


